[

    {
        title: 'Far Cry 3 Blood Dragon',
        price: 25000,
        description: 'Eres el sargento Rex Colt, un cibercomando Tipo Cuatro. Corre el año 2007 y la Tierra ha sido devastada por una guerra nuclear que estalló en los 90. El conflicto entre Oriente y Occidente se ha desarrollado durante generaciones y la humanidad se esfuerza por progresar tras una década de desastres. Es necesario buscar nuevas vías para la paz, y el ejército de cíborgs de los Estados Unidos quizá haya encontrado la solución: una poderosa arma biológica en una lejana isla. Tu misión es reunir información y averiguar qué demonios está pasando.',
        type: 'DLC',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'FPS',
        img: '/images/fc3bd.jpg',
        thumbnail: '/images/fc3bdthum.jpg',
        img1: '/images/fcimg1.jpg',
        img2: '/images/fcimg2.jpg',
        img3: '/images/fcimg3.jpg',
        popularity: 1,
        year: 2007,
    },

    {
        title: 'Gears 5',
        price: 250000,
        description: 'Gears, una de las sagas más aclamadas del mundo de los videojuegos, vuelve más grande que nunca con cinco modos emocionantes y la campaña más elaborada hasta el momento. Al comenzar una guerra sin cuartel, Kait Diaz escapa para investigar su conexión con el enemigo y descubrir el verdadero',
        type: 'Juego',
        platform: 'Epic',
        iconplat: '/images/epicicon.png',
        genre: 'FPS',
        img: '/images/gears5.jpg',
        thumbnail: '/images/gears5thumb.jpg',
        img1: '/images/gears1.jpg',
        img2: '/images/gears2.jpg',
        img3: '/images/gears3.jpg',
        popularity: 2,
        year: 2019,
    },

    {
        title: 'Destiny 2',
        price: 48000,
        description: 'Nuevas pesadillas han surgido de las sombras de la Luna. Impulsada por visiones inquietantes, Eris Morn ha regresado. Únetele para derrotar estas pesadillas antes de que dejen la Luna y sumerjan a la humanidad en otra era oscura.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'FPS',
        img: '/images/destiny2.jpg',
        thumbnail: '/images/destiny2thumb.jpg',
        img1: '/images/destinyimg1.jpg',
        img2: '/images/destinyimg2.jpg',
        img3: '/images/destinyimg3.jpg',
        popularity: 3,
        year: 2019,
    },

    {
        title: 'Code Vein',
        price: 190000,
        description: 'Nos alzamos ante la perspectiva de una muerte segura. Forma equipo y emprende un viaje hasta los confines del infierno para revelar tu pasado y escapar de la pesadilla en vida en CODE VEIN.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'RPG',
        img: '/images/codevein.png',
        thumbnail: '/images/codeveinthumb.jpg',
        img1: '/images/codevein1.jpg',
        img2: '/images/codevein2.jpg',
        img3: '/images/codevein3.jpg',
        popularity: 4,
        year: 2019,
    },

    {
        title: 'GTA V',
        price: 50000,
        description: 'GTA V se ambienta en Los Santos, ciudad ficticia basada en Los Angeles. En cuanto a GTA Online, el multijugador permite hasta 30 jugadores en línea para explorar el mapeado del juego y disputar distintas misiones de forma cooperativa y/o competitiva, además de celebrarse diferentes eventos para mantener la comunidad de GTA V activa. Actualmente, se rumorea que el juego podría tener un DLC de historia (una expansión argumental) protagonizada por un nuevo personaje, aunque de momento Rockstar no se ha pronunciado.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'FPS',
        img: '/images/gtav.jpg',
        thumbnail: '/images/gtavthumb.jpg',
        img1: '/images/gtav1.jpg',
        img2: '/images/gtav2.jpg',
        img3: '/images/gtav3.jpg',
        popularity: 5,
        year: 2013,
    },


    {
        title: 'Project CARS 2',
        price: 196000,
        description: 'Esta nueva entrega ofrece ofrece una gran variedad de carreras para cualquier clase de piloto, con total libertad para elegir qué conducir y dónde hacerlo. Project CARS 2 incluye la mayor lista de circuitos jamás vista en consola, una amplia selección de más de 170 coches con licencia de las marcas más icónicas, y soporte para realidad virtual y 12K. ',
        type: 'Juego',
        platform: 'Epic',
        iconplat: '/images/epicicon.png',
        genre: 'Carreras',
        img: '/images/pcar.jpg',
        thumbnail: '/images/pcarthumb.jpg',
        img1: '/images/pcar1.jpg',
        img2: '/images/pcar2.jpg',
        img3: '/images/pcar3.jpg',
        popularity: 6,
        year: 2017,
    },


    {
        title: 'DiRT Rally',
        price: 54500,
        description: 'Es la segunda entrega de la saga de conducción Dirt con la licencia oficial de la FIA World Rallycross Championship con vehículos de toda la historia de la competición. Ábrete camino a través de una selección de ubicaciones de rally icónicas por todo el mundo, en los vehículos todoterreno más potentes de la historia, teniendo en cuenta que el menor de los fallos puede poner fin a tu carrera.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'Carreras',
        img: '/images/dirtr.jpg',
        thumbnail: '/images/dirtrthumb.jpg',
        img1: '/images/dirtr1.jpg',
        img2: '/images/dirtr2.jpg',
        img3: '/images/dirtr3.jpg',
        popularity: 7,
        year: 2015,
    },


    {
        title: 'BioShock Infinite',
        price: 15000,
        description: 'BioShock pega el salto a los cielos con BioShock Infinite, la tercera entrega de la aclamado franquicia first person shooter desarrollada por Irrational Games y publicada por 2K Games para PlayStation 3, Xbox 360 y PC; una nueva utopía de la mano de Ken Levine.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'Aventura',
        img: '/images/bio.jpg',
        thumbnail: '/images/biothumb.jpg',
        img1: '/images/bio1.jpg',
        img2: '/images/bio2.jpg',
        img3: '/images/bio3.jpg',
        popularity: 8,
        year: 2013,
    },


    {
        title: 'MONSTER HUNTER: WORLD',
        price: 175000,
        description: 'Monster Hunter World, desarrollado y distribuido por Capcom para PC, PlayStation 4 y Xbox One, es una nueva entrega de la popular saga de acción y aventura en la que su vertiente social se potenciará más que nunca y con multitud de opciones de creación y personalización de armas y equipamiento.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'Aventura',
        img: '/images/monster.jpg',
        thumbnail: '/images/monsterthumb.jpg',
        img1: '/images/monster1.jpg',
        img2: '/images/monster2.jpg',
        img3: '/images/monster3.jpg',
        popularity: 9,
        year: 2018,
    },



    {
        title: 'DARK SOULS III',
        price: 109000,
        description: 'Dark Souls III es la tercera entrega de la saga de acción y rol Dark Souls a cargo de From Software y Namco Bandai Games para PC, PlayStation 4 y Xbox One. Presenta novedades en términos jugables con combates más ágiles y más posibilidades de exploración.',
        type: 'Juego',
        platform: 'Epic',
        iconplat: '/images/epicicon.png',
        genre: 'RPG',
        img: '/images/dsIII.jpg',
        thumbnail: '/images/dsIIIthumb.jpg',
        img1: '/images/dsIII1.jpg',
        img2: '/images/dsIII2.jpg',
        img3: '/images/dsIII3.jpg',
        popularity: 10,
        year: 2016,
    },


    {
        title: 'Mad Max',
        price: 50000,
        description: 'La Mad Max key ofrece un punto de acceso al mundo de la franquicia que ha sido vital para la carrera de Mel Gibson y ha emocionado a los fans del cine durante décadas. En la adaptación al videojuego de la frMad Max keyanquicia, juegas como Mad Max, un reacio héroe que tiene que preparar su coche para viajar por todo el Yermo, intentando sobrevivir contra bandas de criminales, incluso luchando fuera de su coche cuando la situación lo necesita.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'Aventura',
        img: '/images/madmax.jpg',
        thumbnail: '/images/madmaxthumb.jpg',
        img1: '/images/madmax1.jpg',
        img2: '/images/madmax2.jpg',
        img3: '/images/madmax3.jpg',
        popularity: 11,
        year: 2015,
    },


    {
        title: 'The Crew 2',
        price: 180000,
        description: 'The Crew 2 es la secuela del juego de conducción online multijugador, que en esta ocasión, además de ofrecer mejores gráficos y modos de juego, nos permite conducir por nuevos medios y superficies. De esta forma, The Crew 2 añade aviones y lanchas, circuitos acuáticos y más opciones de configuración.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'Carreras',
        img: '/images/thecrew2.jpg',
        thumbnail: '/images/thecrew2thumb.jpg',
        img1: '/images/thecrew21.jpg',
        img2: '/images/thecrew22.jpg',
        img3: '/images/thecrew23.jpg',
        popularity: 12,
        year: 2018,
    },

    {
        title: 'Fable Anniversary',
        price: 67000,
        description: 'Fable Anniversary para Xbox 360 es una remasterización HD del primer Fable lanzado para la consola Xbox en el año 2003, con gráficos actualizados a 1080 HD, y con el mismo estilo del original, que llamaba la atención por modificar en tiempo real el aspecto de nuestro personaje dependiendo de la moralidad de sus acciones. El título cuenta con una nueva interfaz, nuevo sistema de iluminación, texturas y modelados de personajes, además de incluir soporte para SmartGlass y el capítulo "The Lost Chapters" que hizo de expansión del primer juego. Cuenta también con logros.',
        type: 'Juego',
        platform: 'Epic',
        iconplat: '/images/epicicon.png',
        genre: 'RPG',
        img: '/images/fable.jpg',
        thumbnail: '/images/fablethumb.jpg',
        img1: '/images/fable1.jpg',
        img2: '/images/fable2.jpg',
        img3: '/images/fable3.jpg',
        popularity: 13,
        year: 2014,
    },

    {
        title: 'Battlefield 5',
        price: 80000,
        description: 'Este increíble juego FPS está de vuelta. EA Games vuelve al mercado con Battlefield V, que en esta ocasión se centra en uno de los eventos más intensos y horribles del pasado que cambió el eje del poder en todo el mundo, la Segunda Guerra Mundial. Con un manejo mejorado, muchas opciones de personalización, nuevas experiencias multijugador, una variedad de historias de guerra únicas creadas para un solo jugador en su modo campaña, nuevo contenido cooperativo y sus impresionantes gráficos y efectos visuales hacen que este juego de acción nos envuelva y situe en la batalla más que nunca.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'FPS',
        img: '/images/bfv.jpg',
        thumbnail: '/images/bfvthumb.jpg',
        img1: '/images/bfv1.jpg',
        img2: '/images/bfv2.jpg',
        img3: '/images/bfv3.jpg',
        popularity: 14,
        year: 2018,
    },


    {
        title: 'Red Dead Redemption 2',
        price: 200000,
        description: 'Desarrollado por Rockstar Games, Red Dead Redemption 2 es la secuela al juego de western de mundo abierto con el mismo nombre lanzado en 2010. Compra Red Dead Redemption 2 PC key y disfruta de una nueva experiencia gaming de Rockstar, tan épica como las que nos tienen acostumbrados. Como Red Dead Redemption 2 viene de las consolas al PC, habrá un par de cambios y añadidos que mejoran la ya excelente nueva entrega de esta franquicia del Salvaje Oeste.',
        type: 'Juego',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'Aventura',
        img: '/images/reddeadii.jpg',
        thumbnail: '/images/reddeadiithumb.jpg',
        img1: '/images/reddeadii1.jpg',
        img2: '/images/reddeadii2.jpg',
        img3: '/images/reddeadii3.jpg',
        popularity: 15,
        year: 2019,
    },


    {
        title: 'Haydee',
        price: 25000,
        description: '"Haydee" is a hardcore old-style metroidvania mixed with modern-day third person shooter and platformer mechanics. As well as a sexy character.',
        type: 'Juego',
        platform: 'Epic',
        iconplat: '/images/epicicon.png',
        genre: 'Aventura',
        img: '/images/haydee.jpg',
        thumbnail: '/images/haydeethumb.jpg',
        img2: '/images/haydee1.jpg',
        img1: '/images/haydee2.jpg',
        img3: '/images/haydee3.jpg',
        popularity: 16,
        year: 2016,
    },

    {
        title: 'Need for Speed: Heat',
        price: 180000,
        description: 'La franquicia de “conduce o muere” ha vuelto con su nuevo título Heat, ¡aún más intenso que antes! Compra Need for Speed: Heat key y vuelve a las carreras clandestinas, aumenta tu reputación y conviértete en uno de los mejores en las calles. Pero ten cuidado, una nueva amenaza te espera en las carreras nocturnas, y no sólo me refiero a tus oponentes.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'Carreras',
        img: '/images/nfsh.jpg',
        thumbnail: '/images/nfshthumb.jpg',
        img2: '/images/nfsh1.jpg',
        img1: '/images/nfsh2.jpg',
        img3: '/images/nfsh3.jpg',
        popularity: 17,
        year: 2019,
    },


    {
        title: 'Overwatch',
        price: 50000,
        description: 'Overwatch es un juego de disparos lleno de héroes, en el que los jugadores se dividen en equipos de seis personas con la posibilidad de seleccionar el héroe deseado de una lista que se actualiza constantemente. Cada héroe posee habilidades únicas, por lo que hay muchas posibilidades para que desarrolles tus propias estrategias al tiempo que impones tu estilo de juego.',
        type: 'Juego',
        platform: 'Origin',
        iconplat: '/images/originicon.png',
        genre: 'FPS',
        img: '/images/ow.jpg',
        thumbnail: '/images/owthumb.jpg',
        img2: '/images/ow1.jpg',
        img1: '/images/ow2.jpg',
        img3: '/images/ow3.jpg',
        popularity: 18,
        year: 2016,
    },


    {
        title: 'Paladins',
        price: 30000,
        description: 'Paladins: Champions of the Realm es un shooter online desarrollado por Hi-Rez para consolas y PC. Con elementos de MOBA, en el que los diferentes personajes tienen un gran peso en los encuentros y partidas, el videojuego pretende competir contra otras propuestas similares en el género aportando mecánicas nuevas y añadiendo interesantes opciones jugables.',
        type: 'DLC',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'FPS',
        img: '/images/paladins.jpg',
        thumbnail: '/images/paladinsthumb.jpg',
        img2: '/images/paladins1.jpg',
        img1: '/images/paladins2.jpg',
        img3: '/images/paladins3.jpg',
        popularity: 19,
        year: 2016,
    },
    
    {
        title: 'Shadow of Mordor',
        price: 10000,
        description: 'En este RPG de acción de mundo abierto, juegas como un montaraz de nombre Talion, cuya familia ha sido asesinada, y tú has estado a punto de sufrir el mismo destino. Sin embargo, Middle Earth: Shadow of Mordor introduce el anciano espectro del Señor Elfo Celebrimbor que te ofrece la opción de crear un vínculo sagrado, y te da una serie de habilidades de espectro, con las que podrás llevar a cabo una guerra unipersonal contra las legiones de Sauron.',
        type: 'DLC',
        platform: 'Steam',
        iconplat: '/images/steamicon.png',
        genre: 'FPS',
        img: '/images/shadow.jpg',
        thumbnail: '/images/shadowthumb.jpg',
        img2: '/images/shadow1.jpg',
        img1: '/images/shadow2.jpg',
        img3: '/images/shadow3.jpg',
        popularity: 20,
        year: 2014,
    },





]